name: sample_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  go_router: ^14.2.0
  http: ^1.2.2
  uuid: ^3.0.7
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  sqflite_common_ffi_web: ^0.3.1
  dev_test: ^1.0.1

dev_dependencies:
dev_test: ^1.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
