name: resume_builder
description: "A Resume Builder project with MVVM architecture."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  go_router: ^14.2.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  uuid: ^4.2.1
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true